use_frameworks!

target 'MoyaManager_Example' do
  pod 'MoyaManager', :path => '../'

  target 'MoyaManager_Tests' do
    inherit! :search_paths

#    pod 'Quick', '~> 1.2.0'
#    pod 'Nimble', '~> 7.0.2'
  end
end
